### PR TITLE
Proper custom color handling

### PR DESCRIPTION
**Pull request by SilverCory**
https://docs.microsoft.com/en-gb/windows/desktop/api/commdlg/ns-commdlg-tagchoosecolora

The Microsoft documentation says that type `LpCustColors` is as follows:
>A pointer to an array of 16 values that contain red, green, blue (RGB) values for the custom color boxes in the dialog box. If the user modifies these colors, the system updates the array with the new RGB values.

### CODE REVIEW

**Comment by lxn** [comment]
Sorry for the late response.

It works either way, but your change seems preferable.

Please add yourself to the AUTHORS file.

Thanks!

**Comment by SilverCory** [comment]
It works but the custom colours wouldn't work from what I could tell. Either that or I've misunderstood something about ColourRef?

Will do, thanks for accepting the PR.

**Comment by lxn** [comment]
Nothing special about `COLORREF`. You just would have initialized `LpCustColors` to the first item in the array, just like with C. But I actually prefer your change, so thank you!

**Comment by SilverCory** [comment]
Ahhh okay, I wouldn't have thought that would work. Nice talking to you! :)

**Pull request merged**
